# Source: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        build_type: [Release]
        compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            compiler: ""
          - os: ubuntu-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: clang

    steps:
    - uses: actions/checkout@v4

    - name: Build and run tests (Windows)
      if: matrix.os == "windows-latest"
      run: |
        nmake -f Makefile.win64
        
        Get-ChildItem "." -Filter '*.cpp' | 
        Foreach-Object {
          Write-Output "--- RUNNING $_ ---"
            Invoke-Expression $_
          Write-Output "--- done RUNNING $_ ---"
        }

      working-directory: ${{ github.workspace }}/test
      shell: pwsh

    - name: Build and run tests (Ubuntu)
      if: matrix.os == "ubuntu-latest"
      run: |
        make -f Makefile.linux64.${{ matrix.compiler }}
        
        for f in $(find . -type f -name "*.cpp"); do
          f=${f%.cpp}
          echo "--- RUNNING $f ---"
            ${f}
          echo "--- done RUNNING $f ---"
        done
      working-directory: ${{ github.workspace }}/test
      shell: bash
